### ISSUE TITLE
Ticket12 Механізм авторизації та аутентифікації

### ISSUE THREAD

**Issue by bobantonbob** [IT-School-GoIT/FinalProjectGoitWeb#12]
- Реалізація механізму реєстрації та входу користувачів:

Створення сторінок реєстрації та входу користувача, включаючи форми та контролери.

- Забезпечення обмеженого доступу для авторизованих користувачів:

Налаштування доступу до функціоналу лише для авторизованих користувачів.

- Написання механізму відновлення паролю за допомогою email:

Розробка функціоналу для відновлення забутого паролю за допомогою електронної пошти.

**Comment by bobantonbob** [comment]
![Image](https://github.com/IT-School-GoIT/FinalProjectGoitWeb/assets/130400459/51198069-7bdf-443c-84c9-455937210850)

**Comment by bobantonbob** [comment]
![Image](https://github.com/IT-School-GoIT/FinalProjectGoitWeb/assets/130400459/23322766-5e16-4dd4-8a89-8ed059f818f1)

**Comment by bobantonbob** [comment]
![Image](https://github.com/IT-School-GoIT/FinalProjectGoitWeb/assets/130400459/4dc26b5c-2198-4796-beb1-16810bfe1693)

Вхід з а допомогою емаіл, після натискання скидання паролю

**Comment by bobantonbob** [comment]
![Image](https://github.com/IT-School-GoIT/FinalProjectGoitWeb/assets/130400459/215145c1-e68b-4fd4-8858-42a779301fb0)

це пи регістрації за допомогою google

**Comment by bobantonbob** [comment]
зникла можливість видалення 

![Image](https://github.com/IT-School-GoIT/FinalProjectGoitWeb/assets/130400459/7ffe843a-4d7b-402a-a277-ae22e71b80b7)

**Comment by VBit7** [comment]
mail account is blocked, you need to unblock it
