### ISSUE TITLE
Ticket9 Робота з файлами в хмарі. Підключення бекенду до фронтенду

### ISSUE THREAD

**Issue by bobantonbob** [IT-School-GoIT/FinalProjectGoitWeb#24]
Робота з файлами в хмарі. Підключення бекенду до фронтенду

1. Підключення бекенду до фронтенду:
- Реалізувати механізм взаємодії між бекендом і фронтендом для передачі даних.
- Забезпечити коректну обробку запитів та відповідей між бекендом і фронтендом.

2. Розробка сторінки для завантаження файлів на сервер:
- Створити веб-інтерфейс для завантаження файлів на сервер.
- Реалізувати форму для вибору файлу для завантаження з можливістю вибору одного або кількох файлів.

3. Розробка функціоналу для вибору категорії файлу при завантаженні:
- Додати можливість вибрати категорію для завантаженого файлу з передбачених варіантів.
- Забезпечити передачу обраної категорії разом із файлом на сервер.

4. Відображення категорій файлів на веб-інтерфейсі для користувача:
- Показати доступні категорії файлів на веб-інтерфейсі для користувача для вибору під час завантаження файлу.

5. Додавання можливості скачування файлів через веб-інтерфейс:
- Реалізувати можливість перегляду списку завантажених файлів та їх скачування через веб-інтерфейс.

6. Забезпечення безпеки при скачуванні файлів:
Врахувати права доступу користувача при скачуванні файлів, забезпечивши конфіденційність та цілісність даних.
Застосувати відповідні методи аутентифікації та авторизації для контролю доступу до файлів.

**Comment by VBit7** [comment]
Task complete
